### ISSUE TITLE
Help me find application  amazon advertising 

### ISSUE THREAD

**Issue by JBLathiya** [lincolnaleixo/amazon-advertising#1]
Hey can you give client id and client secret for testing amazon advertising api.
this is only for testing.i try to whitelist my application but amazon whitelist someone other client id 
can you give first authorization url with fill required parameter i can test my api please you help me 
then mail on this email :-  jaydeep@rentechdigital.com

**Comment by lincolnaleixo** [comment]
Hey @JBLathiya 
You can use the sandbox environment: https://advertising.amazon.com/API/docs/en-us/get-started/sandbox-environment
